language: rust
sudo: false
cache: cargo

rust:
  - stable
script:
  - cargo build --verbose --release --workspace --manifest-path src/Cargo.toml

matrix:
  # Performance tweak
  fast_finish: true

  include:
    # Linux
    #- env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx
    #- env: TARGET=aarch64-apple-darwin
    #  os: osx
      
    # Windows
    #- env: TARGET=x86_64-pc-windows-gnu