name: Rust

on: [push]

jobs:

  build-linux-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Step Settings
        id: settings
        run: |
            echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}
            echo ::set-output name=TARGET_NAME::x86_64-unknown-linux-musl
      - uses: actions/checkout@master
      - name: Build and Test
        uses: zhxiaogg/cargo-static-build@master
        with:
          cmd: cargo build --manifest-path=src/Cargo.toml --release --target ${{ steps.settings.outputs.TARGET_NAME }}