name: Rust

on: [push]

jobs:

  build-linux-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Step Settings
        id: settings
        run: |
            echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}
            echo ::set-output name=TARGET_NAME::x86_64-unknown-linux-musl
      - uses: actions/checkout@master
      - name: Build and Test
        uses: zhxiaogg/cargo-static-build@master
        with:
          cmd: cargo build --manifest-path=src/Cargo.toml --release --target ${{ steps.settings.outputs.TARGET_NAME }}

  build-linux-x86_64:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')

    steps:
      #set some environement variables that we can use through the rest of our
      #action
      - name: Step Settings
        id: settings
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=TARGET_NAME::x86_64-unknown-linux-gnu

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ steps.settings.outputs.TARGET_NAME }}
          override: true
      - uses: actions-rs/cargo@v1
        env:
          DESTINY_API_KEY: ${{ secrets.DESTINY_API_KEY }}
        with:
          use-cross: true
          command: build
          args: --manifest-path=src/Cargo.toml